/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 376018f7ef354f389a3eb45ad22db42a)
interface __BaseEnv_Env {
  WORKER_VERSION: WorkerVersionMetadata
  SOURCE_ORIGIN: "https://filerouter.dev"
  PDF_INSPECTOR_CONTAINERS: DurableObjectNamespace<
    import("./src/index").PdfInspectorContainer
  >
  LITEPARSE_CONTAINERS: DurableObjectNamespace<
    import("./src/index").LiteParseContainer
  >
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index")
    durableNamespaces: "PdfInspectorContainer" | "LiteParseContainer"
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "SOURCE_ORIGIN">
  > {}
}
